### ISSUE TITLE
As a User, I want a stylized template to use in cover letters

### ISSUE THREAD

**Issue by Jonathan-Zollinger** [Jonathan-Zollinger/Go-getajob#7]
## Overview
Create a cover letter template which maintains style yet allows additions 

### Additional Context
- Cover letter is to be generated from this document (iow this will be a PDF in the end)

### Blocking User Stories / feature requests
\-

### Defining `Done`
- Document can be edited
- Document's style persists through edits
- PDF can be generated from document

**Comment by bsantarossa** [comment]
This would be more of a part of accomplishing the user story #1. Think of user stories as a feature that can be manipulated by the user. If they cannot choose different template, then this would not be a feature.

**Comment by Jonathan-Zollinger** [comment]
good point, thanks Brian :)
